### PR TITLE
fix: do not download pnpm from get.pnpm.io

### LINKED ISSUE #22: Pipelines fail with `SyntaxError: Unexpected token`
Hi, we see occasional failed pipelines because, well, **something** goes wrong in `pnpm/action-setup`:

```
Running self-installer...
  [stdin]:1
  <HTML>
  ^
  SyntaxError: Unexpected token '<'
      at new Script (vm.js:84:7)
      at createScript (vm.js:258:10)
      at Object.runInThisContext (vm.js:306:10)
      at Object.<anonymous> ([stdin]-wrapper:9:26)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at evalScript (internal/process/execution.js:80:25)
      at internal/main/eval_stdin.js:29:5
      at Socket.<anonymous> (internal/process/execution.js:192:5)
      at Socket.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
Error: Something does wrong, self-installer exits with code 1
Installation Completed!
Running pnpm recursive install --frozen-lockfile
Error: Command pnpm recursive install --frozen-lockfile (cwd: undefined) exits with status 127
```

I'm not sure if it's [this line](https://github.com/pnpm/action-setup/blob/master/src/install-pnpm/run.ts#L22) `const response = await fetch('https://pnpm.js.org/pnpm.js')` that might fail? If it somehow gets an HTML response? So if pnpm.js.org fails to return the `pnpm.js` script for a splitsecond, instead returning an HTML error page, then that could happen?

Will maintainers consider a retry mechanism to increase resilience? If the request is the cause of this error then an exponential backoff could work well, to try a couple times before giving up. WDYT?

### LINKED ISSUE #44: MacOS 11: Something went wrong, self-installer exits with code 1
The action fails on MacOS 11
https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:1
```js
Run pnpm/action-setup@v[2](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:2)
  with:
    version: 7
    dest: ~/setup-pnpm
    run_install: null
Running self-installer...
  [stdin]:1
  <!DOCTYPE html>
  ^
  
  SyntaxError: Unexpected token '<'
      at new Script (vm.js:88:7)
      at createScript (vm.js:261:10)
      at Object.runInThisContext (vm.js:[3](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:3)09:10)
      at Object.<anonymous> ([stdin]-wrapper:10:26)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at evalScript (internal/process/execution.js:9[4](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:4):2[5](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:5))
      at internal/main/eval_stdin.js:29:5
      at Socket.<anonymous> (internal/process/execution.js:207:5)
      at Socket.emit (events.js:32[6](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:7):22)
      at endReadableNT (_stream_readable.js:[12](https://github.com/aminya/setup-cpp/runs/6601627749?check_suite_focus=true#step:5:13)41:12)
Error: Something went wrong, self-installer exits with code 1
Installation Completed!
```

### PR DESCRIPTION
**Pull request by zkochan**
close #44
close #22

### CODE REVIEW

**Comment by KSXGitHub** [comment]
This would effectively render the `version` input key pointless. Is this your intention?

**Comment by zkochan** [comment]
Not correct.

Nothing changed. pnpm is installing the specified version of pnpm. Before this change, pnpm was downloaded. This was causing issues. So now the pnpm which installs pnpm is committed to the project.

**Comment by KSXGitHub** [comment]
Ah, I see. I somehow forgot the workings of the code that I wrote/merged myself lol.

**Comment by zkochan** [comment]
Could you release it? I don't know how it is released.

**Review by KSXGitHub — CHANGES_REQUESTED** [review]
So there are 2 `pnpm.js` files: One in `dist`, the other in `src/install-pnpm`. Is this excessive?

**Comment by zkochan** [comment]
it might be

why is the dist folder committed at all?

**Comment by KSXGitHub** [comment]
Wait, did you just merge? I was meant to make more review comment!

**Comment by zkochan** [comment]
ok, comment, I'll make another PR

**Comment by KSXGitHub** [comment]
> Could you release it? I don't know how it is released.

Step 0: Make sure that you have enabled Two Factor Authentication (2-FA) on GitHub.
Step 1: Use `git tag` to tag a version (and then push the tag).
Step 2: Go to the Release Page on GitHub.
Step 3: Click on the tag.
Step 4: Create a release.
Step 5: Remember to check the Marketplace checkbox.

**Comment by zkochan** [comment]
Thanks, we'll have to add that to a CONTRIBUTING.md

**Comment by KSXGitHub** [comment]
> why is the dist folder committed at all?

The `dist` contains `index.js` which is what the "engine" of GitHub Actions would execute. Because the "engine" can't understand TypeScript.

**Comment by zkochan** [comment]
can we generate it before packing?

**Comment by KSXGitHub** [comment]
> can we generate it before packing?

I think there's a command in `package.json` that generates `dist/index.js`. I always make sure to execute it before commit, [though not automatically yet](https://github.com/pnpm/action-setup/issues/34).

**Pull request merged**
