### PR TITLE
Adds documentation hints for caching

### LINKED ISSUE #8: Enhancement: cache pnpm-store
Correct caching of the `~/.pnpm-store` directory would be cool.

See https://github.com/bahmutov/npm-install for one approach to get ideas from

### PR DESCRIPTION
**Pull request by hildjj**
Fixes #8.
See example in action here: https://github.com/hildjj/node-cbor/actions/runs/569755485

### CODE REVIEW

**Review by KSXGitHub — CHANGES_REQUESTED** [review]
I prefer this to be a code snippet under `## Usage Example` section.

**Comment by hildjj** [comment]
Willfix

**Review by KSXGitHub — CHANGES_REQUESTED** [review]
Your code snippet is not a working example. You need to add 2 steps: `actions/checkout` and `pnpm/action-setup`.

You may use other existing code snippets for reference.

**Comment by hildjj** [comment]
I would be happy to change the other pnpm version numbers in the examples to 5.17.2 (or whatever you'd prefer) for consistency if you like.

**Pull request merged**
