### PR TITLE
Install the self-contained binary version of pnpm

### LINKED ISSUE #18: Feature request: run pnpm with old version node
### What

This is a feature request to this action supports run pnpm@6 in node@10 environment.

### Why

I use pnpm@6 in local dev, but my package wants to support `node>=10`, which break the rule of pnpm@6, engines.node >=12.

### Detail

add a parameter (maybe named `compiled_install`),
If true, instead of install pnpm directly, run sth like `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm` to setup a compiled pnpm binary as `pnpm` CLI

### PR DESCRIPTION
**Pull request by zkochan**
This is a breaking change because the binary version of pnpm is only available from v6.17.1. 
Also, it doesn't ship `pnpx`.

close #18

### CODE REVIEW

**Review by KSXGitHub — CHANGES_REQUESTED** [review]
1. You intend to drop support for pnpm versions without self-contained binary, correct? If that's the case, why even bother running the self-installer and install it via the npm registry at all? Why not just download the binary directly from [GitHub release](https://github.com/pnpm/pnpm/releases)?
2. Can you add code that check for unsupported pnpm versions before download? If user specify a pnpm version that doesn't have self-contained binary, it is more user-friendly to inform the user about it than an ambiguous 404.
3. Can you update the README.md file? Some information in README.md is ought to be outdated after this PR.
4. Finally, please remember to update `dist/index.js` before commit.

**Comment by KSXGitHub** [comment]
**Amendment:**

> You intend to drop support for pnpm versions without self-contained binary, correct? If that's the case, why even bother running the self-installer and install it via the npm registry at all? Why not just download the binary directly from [GitHub release](https://github.com/pnpm/pnpm/releases)?

GitHub Release does not support version ranges (e.g. `^6.17.1`), so we must resolve to the correct version ourselves. Or just fallback to npm. Or drop support for version ranges entirely.

**Comment by KSXGitHub** [comment]
@zkochan When will you resolve my requests for change in this PR?

**Comment by zkochan** [comment]
I have to think about it. Not soon.

**Comment by privatenumber** [comment]
Curious if this would be easier to move forward with if it's opt-in via an option (eg. `binary: true`)?

**Comment by tksst** [comment]
I agree with @privatenumber .
Since this branch is very old and differs significantly from the latest master, I forked this action and [implemented an option to install a self-contained binary](https://github.com/tksst/action-setup-pnpm/tree/self-contained-binary).

I will post another PR after I add the test and update the readme.

**Comment by fz6m** [comment]
Good job @tksst .

I think adding a `node-version` option, detect it and auto switch `pnpm@version` to `@pnpm/exe@version` is better.

e.g.

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          # in node 14.x env, we auto install `@pnpm/exe` instead of `pnpm`
          # refer: https://pnpm.io/installation#compatibility
          node-version: ${{ matrix.node-version }}
          version: 8
```

**Comment by tksst** [comment]
@fz6m 

> I think adding a `node-version` option, detect it and auto switch `pnpm@version` to `@pnpm/exe@version` is better.

That is a nice feature, but a bit complicated.  
I may try to implement it when I have time.

**Pull request closed without merging**
